create table if not exists public.daily_revenues (
  id bigint generated by default as identity primary key,
  revenue_date date not null unique,
  cash_amount numeric(12,2) not null default 0 check (cash_amount >= 0),
  card_amount numeric(12,2) not null default 0 check (card_amount >= 0),
  other_amount numeric(12,2) not null default 0 check (other_amount >= 0),
  total_amount numeric(12,2) not null default 0 check (total_amount >= 0),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists daily_revenues_date_idx
  on public.daily_revenues (revenue_date desc);

alter table public.daily_revenues enable row level security;

create policy "panel users can read daily revenues"
  on public.daily_revenues for select to anon, authenticated using (true);

create policy "panel users can insert daily revenues"
  on public.daily_revenues for insert to anon, authenticated with check (true);

create policy "panel users can update daily revenues"
  on public.daily_revenues for update to anon, authenticated using (true) with check (true);
