create table if not exists public.expiry_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  product_name text not null check (length(trim(product_name)) > 0),
  quantity integer not null default 1 check (quantity >= 0),
  location text not null check (location in ('Dolap', 'Depo', 'Tezgah')),
  expiry_date date not null,
  active boolean not null default true,
  note text,
  acknowledged_at timestamptz null,
  acknowledged_note text null
);

alter table public.expiry_items
  add column if not exists acknowledged_at timestamptz null;

alter table public.expiry_items
  add column if not exists acknowledged_note text null;

create index if not exists expiry_items_active_date_idx
  on public.expiry_items (active, expiry_date);

alter table public.expiry_items enable row level security;

create policy "panel users can read expiry items"
  on public.expiry_items for select to anon, authenticated using (true);

create policy "panel users can insert expiry items"
  on public.expiry_items for insert to anon, authenticated with check (true);

create policy "panel users can update expiry items"
  on public.expiry_items for update to anon, authenticated using (true) with check (true);
